version: '3.1'

services:
  redis:
    image: redis/redis-stack:latest
    restart: unless-stopped
    ports:
      - "6379"
      - "8001"
    volumes:
      - redis_data:/data
    networks:
      - default
      
  backend:
    # build: ../..
    # image: tds-backend
    image: docker-registry-bitmosys.surajkhayamali.com.np/tds-backend
    restart: unless-stopped
    ports:
      - "${PORT}"
    environment:
      - NODE_ENV=production
      - PORT=${PORT}

      - MONGODB_CLIENT_URL=${MONGODB_CLIENT_URL}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_SEED=${DATABASE_SEED}
      
      - SALT_ROUNDS=${SALT_ROUNDS}

      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - JWT_REFRESH_EXPIRES_IN=${JWT_REFRESH_EXPIRES_IN}

      - COOKIE_SECRET=${COOKIE_SECRET}
      - COOKIE_MAX_AGE=${COOKIE_MAX_AGE}
      - COOKIE_REFRESH_MAX_AGE=${COOKIE_REFRESH_MAX_AGE}

      - FASTIFY_SECURE_SESSION_SECRET=${FASTIFY_SECURE_SESSION_SECRET}
      - FASTIFY_SECURE_SESSION_SALT=${FASTIFY_SECURE_SESSION_SALT}

      - LOG_LEVEL=${LOG_LEVEL}

      - CONFIGURE_SWAGGER_DOC=${CONFIGURE_SWAGGER_DOC}

      - FILE_STORAGE_PROVIDER=${FILE_STORAGE_PROVIDER}
      - FILE_STORAGE_PATH_SEPERATOR=${FILE_STORAGE_PATH_SEPERATOR}
      - FILE_SYSTEM_ROOT=${FILE_SYSTEM_ROOT}
      
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_TTL=${REDIS_TTL}
      - REDIS_TTL_FOR_STREAMS=${REDIS_TTL_FOR_STREAMS}

      - CACHE_PROVIDER=${CACHE_PROVIDER}
      - CACHE_TTL=${CACHE_TTL}

      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_FULL_FROM=${SMTP_FULL_FROM}
      - SMTP_REPLY_TO=${SMTP_REPLY_TO}
      - SMTP_REPLY_TO_BOOKING=${SMTP_REPLY_TO_BOOKING}
      - SMTP_REPLY_TO_ADMIN=${SMTP_REPLY_TO_ADMIN}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - BOOKING_EMAIL=${BOOKING_EMAIL}
      - SUPPORT_EMAIL=${SUPPORT_EMAIL}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}

      - TZ=${TZ}

      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_FROM=${TWILIO_FROM}
      - THROTTLE_TTL=${THROTTLE_TTL}
      - THROTTLE_LIMIT=${THROTTLE_LIMIT}
      
      - GET_ADDRESS_IO_API_KEY=${GET_ADDRESS_IO_API_KEY}

      - EXPO_ACCESS_TOKEN=${EXPO_ACCESS_TOKEN}

      - CORS_ORIGIN=https://${ADMIN_DOMAIN},https://${PRACTICE_DOMAIN},${CORS_ORIGIN}
      - CORS_CREDENTIALS=${CORS_CREDENTIALS}

      - AVAILABLE_MEMORY_IN_MB=${AVAILABLE_MEMORY_IN_MB}

      # Domain related
      - VIRTUAL_HOST=${API_DOMAIN}
      - VIRTUAL_PORT=${PORT}
      - LETSENCRYPT_HOST=${API_DOMAIN}
      - LETSENCRYPT_EMAIL=suraj@bitmosys.com
    volumes:
      - uploads_data:/usr/src/app/${FILE_SYSTEM_ROOT}/uploads
    networks:
      - default
      - mongo-replica-set_mongo-database-tier
      - proxy_nginx-proxy-tier

  admin:
    image: docker-registry-bitmosys.surajkhayamali.com.np/tds-admin
    environment:
      - VIRTUAL_HOST=${ADMIN_DOMAIN}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${ADMIN_DOMAIN}
      - LETSENCRYPT_EMAIL=suraj@bitmosys.com
    ports:
      - "80"
    networks:
      - proxy_nginx-proxy-tier

  practice:
    image: docker-registry-bitmosys.surajkhayamali.com.np/tds-practice
    environment:
      - VIRTUAL_HOST=${PRACTICE_DOMAIN}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${PRACTICE_DOMAIN}
      - LETSENCRYPT_EMAIL=suraj@bitmosys.com
    ports:
      - "80"
    networks:
      - proxy_nginx-proxy-tier

volumes:
  redis_data:
  uploads_data:

networks:
  default:
  mongo-replica-set_mongo-database-tier:
    external: true
  proxy_nginx-proxy-tier:
    external: true