x-op-app: &app
  environment:
    OPENPROJECT_HOST__NAME: "${OPENPROJECT_HOST__NAME:-openproject.surajkhayamali.com.np}"

services:
  db:
    environment:
      POSTGRES_STATEMENT_TIMEOUT: 6000

  proxy:
    environment:
      VIRTUAL_HOST: openproject.surajkhayamali.com.np
      # VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: openproject.surajkhayamali.com.np
      LETSENCRYPT_EMAIL: suraj@bitmosys.com
    networks:
      - proxy_nginx-proxy-tier
      
  web:
    <<: *app

networks:
  proxy_nginx-proxy-tier:
    external: true
