# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      - MARIADB_USER=bn_suitecrm
      - MARIADB_DATABASE=bitnami_suitecrm
      - MARIADB_PASSWORD=bitnami123
      - MARIADB_ROOT_PASSWORD=bitmosys-root
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    networks:
      - default
  suitecrm:
    image: docker.io/bitnami/suitecrm:8
    ports:
      - "${HTTP_PORT:-10080}:8080"
      - "${HTTPS_PORT:-10443}:8443"
    environment:
      - SUITECRM_DATABASE_HOST=mariadb
      - SUITECRM_DATABASE_PORT_NUMBER=3306
      - SUITECRM_DATABASE_USER=bn_suitecrm
      - SUITECRM_DATABASE_NAME=bitnami_suitecrm
      - SUITECRM_DATABASE_PASSWORD=bitnami123a

      # Overrides
      - SUITECRM_USERNAME=user
      - SUITECRM_PASSWORD=bitmosys
      - SUITECRM_EMAIL=suraj@bitmosys.com
      - SUITECRM_ENABLE_HTTPS=yes
      - SUITECRM_HOST=${DOMAIN}

      # For ssl and proxy purpose
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=suraj@bitmosys.com
    volumes:
      - 'suitecrm_data:/bitnami/suitecrm'
    depends_on:
      - mariadb
    networks:
      - default
      - proxy_nginx-proxy-tier
      
volumes:
  mariadb_data:
    driver: local
  suitecrm_data:
    driver: local


networks:
  default:
  proxy_nginx-proxy-tier:
    external: true
