version: '3'

services:
  web:
    image: docker-registry-bitmosys.surajkhayamali.com.np/tds-admin
    build: .
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=suraj@bitmosys.com
    ports:
      - "80"
    networks:
      - proxy_nginx-proxy-tier

networks:
  proxy_nginx-proxy-tier:
    external: true