version: "2"

services:
  database:
    image: powertic/percona-docker
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
    # ports:
    #   - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - mauticnet
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --sql-mode=""

  mautic:
    image: mautic/mautic:v4-apache
    volumes:
      - mautic_data:/var/www/html
    environment:
      - MAUTIC_DB_HOST=database
      - MAUTIC_DB_USER=root
      - MAUTIC_DB_PASSWORD=mypassword
      - MAUTIC_DB_NAME=mautic4

      - MAUTIC_TRUSTED_PROXIES=["REMOTE_ADDR"]
      - MAUTIC_URL=https://${DOMAIN}
      - MAUTIC_ADMIN_EMAIL=suraj@bitmosys.com
      - MAUTIC_ADMIN_PASSWORD=bitmosys
      # - MAUTIC_INSTALL_FORCE=true
      - MAUTIC_ADMIN_USERNAME=admin
      - MAUTIC_ADMIN_FIRSTNAME=Admin
      - MAUTIC_ADMIN_LASTNAME=User

      # Custom
      - VIRTUAL_HOST=${DOMAIN}
      # - VIRTUAL_PORT=8880
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=suraj@bitmosys.com
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - mauticnet
      - proxy_nginx-proxy-tier
    ports:
      - "80"

volumes:
  database_data:
  mautic_data:

networks:
  mauticnet:
  proxy_nginx-proxy-tier:
    external: true