version: "2"

services:
  docker-registry:
    image: registry:2
    container_name: docker-registry
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=suraj@bitmosys.com
    ports:
      - "5000"
    networks:
      - proxy_nginx-proxy-tier
    volumes:
      - data:/var/lib/registry

networks:
  proxy_nginx-proxy-tier:
    external: true

volumes:
  data: